#!/usr/bin/env python3
"""Regenerate the long-lived demonstration branches (roadmap item 14).

The five `test/*` branches exist to exercise one ABI outcome each against
the real gate. Hand-maintained, they drifted: when this script was written
all five sat 181 commits behind main, so their reports were dominated by
evidence-comparability problems from an old scanner revision rather than by
the scenario each advertises, and one of them had stopped demonstrating its
own claim entirely (see `demos/manifest.yaml` on `source-api-break`).

A drifted demonstration is worse than a missing one: it still reads as
coverage. So the branches stop being hand-maintained. Each is now
`<base> + one patch`, regenerated from the current default branch, with the
expected-result section of its PR body rendered from the same manifest the
scenario oracle asserts against -- so the body cannot claim one thing while
the oracle checks another.

Modes:

  --check   report drift for every demonstration, exit nonzero if any.
            Reads only; safe anywhere, and what CI runs.
  --write   (re)create the branches locally from the current base.
  --push    force-push them. NEVER implied by --write: these branches carry
            open pull requests, and rewriting them is a deliberate act
            someone should have to ask for by name.
  --body    print the PR-body section for one demonstration.

Regenerating is a force-push by construction -- the branch is reset to the
new base, so its old history is not an ancestor of the new. That is the
intended lifecycle for a generated demonstration branch, and it is exactly
why --push is separate.
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent

#: Delimiters for the generated section of a PR body. Everything between
#: them is owned by this script; everything outside is whatever a human
#: wrote and is preserved by `render_body`.
BODY_BEGIN = "<!-- abicheck-lab-demo-expectation:begin -->"
BODY_END = "<!-- abicheck-lab-demo-expectation:end -->"


class DemoError(RuntimeError):
    pass


def git(*args: str, check: bool = True, capture: bool = True) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=REPO_ROOT,
        text=True,
        capture_output=capture,
    )
    if check and result.returncode != 0:
        raise DemoError(
            f"git {' '.join(args)} failed ({result.returncode}): "
            + (result.stderr or result.stdout or "").strip()
        )
    return (result.stdout or "") if capture else ""


def load_manifest(path: Path) -> list[dict[str, Any]]:
    doc = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    demos = doc.get("demonstrations")
    if not isinstance(demos, list) or not demos:
        raise DemoError(f"{path} declares no demonstrations")
    seen: set[str] = set()
    for demo in demos:
        for field in ("id", "branch", "title", "patch", "expect"):
            if field not in demo:
                raise DemoError(f"demonstration {demo.get('id', '?')!r} is missing {field!r}")
        if demo["id"] in seen:
            raise DemoError(f"duplicate demonstration id {demo['id']!r}")
        seen.add(demo["id"])
        patch = REPO_ROOT / demo["patch"]
        if not patch.is_file() or not patch.stat().st_size:
            raise DemoError(f"{demo['id']}: patch {demo['patch']} is missing or empty")
    return demos


def render_body(demo: dict[str, Any], existing: str = "") -> str:
    """The PR body with its generated section replaced.

    Text outside the markers is preserved verbatim: whoever opened the PR may
    have written context worth keeping, and this script owns only the part it
    can actually derive.
    """
    expect = demo["expect"]
    lines = [
        BODY_BEGIN,
        "",
        "> **Generated demonstration PR.** This branch is regenerated by",
        "> `scripts/gen_demo_prs.py` from `demos/manifest.yaml`; edits made",
        "> directly to it will be overwritten. The section between these",
        "> markers is generated from the same manifest the scenario oracle",
        "> asserts against, so the claim below and the check cannot diverge.",
        "",
        f"**What this demonstrates.** {demo.get('claim', '').strip()}",
        "",
        f"**Expected gate outcome:** {expect.get('gate')} "
        f"(verdict `{expect.get('verdict')}`).",
        "",
    ]
    required = expect.get("required_findings") or []
    forbidden = expect.get("forbidden_findings") or []
    if required:
        lines.append("**Findings this must produce:**")
        lines += [f"- `{f.get('kind')}`" + (f" on `{f['symbol']}`" if f.get("symbol") else "")
                  for f in required]
        lines.append("")
    else:
        lines += ["**Findings this must produce:** none — an unchanged exported surface "
                  "is the point.", ""]
    if forbidden:
        lines.append("**Findings this must NOT produce:**")
        lines += [f"- `{f.get('kind')}`" + (f" on `{f['symbol']}`" if f.get("symbol") else "")
                  for f in forbidden]
        lines.append("")
    lines += [
        "A red gate here is the expected natural result where the table above "
        "says so. The separate `demo_oracle` check is the one that has to be "
        "green: it reads the gate's own report and passes only when the "
        "natural result is exactly this.",
        "",
        BODY_END,
    ]
    generated = "\n".join(lines)

    if BODY_BEGIN in existing and BODY_END in existing:
        head = existing[: existing.index(BODY_BEGIN)]
        tail = existing[existing.index(BODY_END) + len(BODY_END):]
        return head + generated + tail
    if existing.strip():
        return existing.rstrip() + "\n\n" + generated + "\n"
    return generated + "\n"


def base_commit(base_ref: str) -> str:
    return git("rev-parse", base_ref).strip()


def check(demos: list[dict[str, Any]], base_ref: str) -> list[str]:
    """Report drift without touching anything."""
    problems: list[str] = []
    base = base_commit(base_ref)
    for demo in demos:
        branch = demo["branch"]
        remote = f"refs/remotes/origin/{branch.removeprefix('refs/heads/')}"
        head = git("rev-parse", "--verify", "--quiet", remote, check=False).strip()
        if not head:
            problems.append(f"{demo['id']}: {branch} does not exist on origin")
            continue
        behind = git("rev-list", "--count", f"{head}..{base}").strip()
        if behind != "0":
            problems.append(
                f"{demo['id']}: {branch} is {behind} commit(s) behind {base_ref} "
                "-- regenerate it (--write, then --push)"
            )
        # The patch applying cleanly to the CURRENT base is what makes
        # regeneration possible at all; a patch that has rotted needs a human
        # before any branch is rewritten.
        patch = REPO_ROOT / demo["patch"]
        applies = subprocess.run(
            ["git", "apply", "--check", str(patch)],
            cwd=REPO_ROOT, capture_output=True, text=True,
        )
        if applies.returncode != 0:
            problems.append(
                f"{demo['id']}: {demo['patch']} no longer applies to the working tree: "
                + (applies.stderr or "").strip()
            )
    return problems


def write(demos: list[dict[str, Any]], base_ref: str, only: str | None) -> list[str]:
    """Recreate each demonstration branch locally as base + its one patch."""
    written = []
    original = git("rev-parse", "--abbrev-ref", "HEAD").strip()
    if git("status", "--porcelain").strip():
        raise DemoError(
            "the working tree is dirty; regenerating demonstration branches "
            "checks branches out and would lose those changes"
        )
    try:
        for demo in demos:
            if only and demo["id"] != only:
                continue
            branch = demo["branch"]
            git("checkout", "-q", "-B", branch, base_ref)
            git("apply", str(REPO_ROOT / demo["patch"]))
            git("add", "-A")
            git("commit", "-q", "-m", demo["title"])
            written.append(f"{branch} = {base_ref} + {demo['patch']}")
    finally:
        git("checkout", "-q", original, check=False)
    return written


def push(demos: list[dict[str, Any]], only: str | None) -> list[str]:
    pushed = []
    for demo in demos:
        if only and demo["id"] != only:
            continue
        branch = demo["branch"]
        # --force-with-lease, not --force: if someone pushed to a
        # demonstration branch since this checkout last fetched it, that is a
        # human decision this script must not silently discard.
        git("push", "--force-with-lease", "origin", f"{branch}:{branch}")
        pushed.append(branch)
    return pushed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--manifest", type=Path, default=REPO_ROOT / "demos/manifest.yaml")
    parser.add_argument("--base-ref", default="origin/main")
    parser.add_argument("--only", help="act on one demonstration id")
    parser.add_argument("--check", action="store_true", help="report drift, change nothing")
    parser.add_argument("--write", action="store_true", help="recreate the branches locally")
    parser.add_argument("--push", action="store_true", help="force-push the branches")
    parser.add_argument("--body", help="print the PR-body section for this demonstration id")
    args = parser.parse_args(argv)

    if not any((args.check, args.write, args.push, args.body)):
        parser.error("one of --check, --write, --push or --body is required")

    try:
        demos = load_manifest(args.manifest)
        if args.body:
            match = next((d for d in demos if d["id"] == args.body), None)
            if match is None:
                raise DemoError(f"no demonstration {args.body!r}")
            print(render_body(match))
            return 0
        if args.check:
            problems = check(demos, args.base_ref)
            for problem in problems:
                print(f"DRIFT {problem}", file=sys.stderr)
            if problems:
                return 1
            print(f"gen_demo_prs: OK -- {len(demos)} demonstration(s) current against {args.base_ref}")
        if args.write:
            for line in write(demos, args.base_ref, args.only):
                print(f"wrote {line}")
        if args.push:
            for branch in push(demos, args.only):
                print(f"pushed {branch}")
    except DemoError as exc:
        print(f"gen_demo_prs: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
