#!/usr/bin/env python3
"""Regenerate the long-lived demonstration branches (roadmap item 14).

The five `test/*` branches exist to exercise one ABI outcome each against
the real gate. Hand-maintained, they drifted: when this script was written
all five sat 181 commits behind main, so their reports were dominated by
evidence-comparability problems from an old scanner revision rather than by
the scenario each advertises, and one of them had stopped demonstrating its
own claim entirely (see `demos/manifest.yaml` on `source-api-break`).

A drifted demonstration is worse than a missing one: it still reads as
coverage. So the branches stop being hand-maintained. Each is now
`<base> + one patch`, regenerated from the current default branch, with the
expected-result section of its PR body rendered from the same manifest the
scenario oracle asserts against -- so the body cannot claim one thing while
the oracle checks another.

Modes:

  --check   report drift for every demonstration, exit nonzero if any.
            Reads only, so it is safe anywhere. The `demo_branch_drift` job
            in abi-scan.yml runs it on every PR and renders the result into
            the job summary. That job is deliberately NON-gating: the only
            way to clear real drift is the force-push below, which rewrites
            branches carrying open pull requests, and a red required check
            cannot make that decision for anyone. It reports; a human acts.
  --write   (re)create the branches locally from the current base.
  --push    force-push them. NEVER implied by --write: these branches carry
            open pull requests, and rewriting them is a deliberate act
            someone should have to ask for by name.
  --body    print the PR-body section for one demonstration.

Regenerating is a force-push by construction -- the branch is reset to the
new base, so its old history is not an ancestor of the new. That is the
intended lifecycle for a generated demonstration branch, and it is exactly
why --push is separate.
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent

#: Delimiters for the generated section of a PR body. Everything between
#: them is owned by this script; everything outside is whatever a human
#: wrote and is preserved by `render_body`.
BODY_BEGIN = "<!-- abicheck-lab-demo-expectation:begin -->"
BODY_END = "<!-- abicheck-lab-demo-expectation:end -->"


class DemoError(RuntimeError):
    pass


def git(*args: str, check: bool = True, capture: bool = True,
        env: dict[str, str] | None = None) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=REPO_ROOT,
        text=True,
        capture_output=capture,
        env=env,
    )
    if check and result.returncode != 0:
        raise DemoError(
            f"git {' '.join(args)} failed ({result.returncode}): "
            + (result.stderr or result.stdout or "").strip()
        )
    return (result.stdout or "") if capture else ""


def load_manifest(path: Path) -> list[dict[str, Any]]:
    doc = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    demos = doc.get("demonstrations")
    if not isinstance(demos, list) or not demos:
        raise DemoError(f"{path} declares no demonstrations")
    seen: set[str] = set()
    for demo in demos:
        for field in ("id", "branch", "title", "patch", "expect"):
            if field not in demo:
                raise DemoError(f"demonstration {demo.get('id', '?')!r} is missing {field!r}")
        if demo["id"] in seen:
            raise DemoError(f"duplicate demonstration id {demo['id']!r}")
        seen.add(demo["id"])
        patch = REPO_ROOT / demo["patch"]
        if not patch.is_file() or not patch.stat().st_size:
            raise DemoError(f"{demo['id']}: patch {demo['patch']} is missing or empty")
    return demos


def render_body(demo: dict[str, Any], existing: str = "") -> str:
    """The PR body with its generated section replaced.

    Text outside the markers is preserved verbatim: whoever opened the PR may
    have written context worth keeping, and this script owns only the part it
    can actually derive.
    """
    expect = demo["expect"]
    lines = [
        BODY_BEGIN,
        "",
        "> **Generated demonstration PR.** This branch is regenerated by",
        "> `scripts/gen_demo_prs.py` from `demos/manifest.yaml`; edits made",
        "> directly to it will be overwritten. The section between these",
        "> markers is generated from the same manifest the scenario oracle",
        "> asserts against, so the claim below and the check cannot diverge.",
        "",
        f"**What this demonstrates.** {demo.get('claim', '').strip()}",
        "",
        f"**Expected gate outcome:** {expect.get('gate')} "
        f"(verdict `{expect.get('verdict')}`).",
        "",
    ]
    required = expect.get("required_findings") or []
    forbidden = expect.get("forbidden_findings") or []
    if required:
        lines.append("**Findings this must produce:**")
        lines += [f"- `{f.get('kind')}`" + (f" on `{f['symbol']}`" if f.get("symbol") else "")
                  for f in required]
        lines.append("")
    else:
        lines += ["**Findings this must produce:** none — an unchanged exported surface "
                  "is the point.", ""]
    if forbidden:
        lines.append("**Findings this must NOT produce:**")
        lines += [f"- `{f.get('kind')}`" + (f" on `{f['symbol']}`" if f.get("symbol") else "")
                  for f in forbidden]
        lines.append("")
    lines += [
        "A red gate here is the expected natural result where the table above "
        "says so. The separate `demo_oracle` check is the one that has to be "
        "green: it reads the gate's own report and passes only when the "
        "natural result is exactly this.",
        "",
        BODY_END,
    ]
    generated = "\n".join(lines)

    if BODY_BEGIN in existing and BODY_END in existing:
        head = existing[: existing.index(BODY_BEGIN)]
        tail = existing[existing.index(BODY_END) + len(BODY_END):]
        return head + generated + tail
    if existing.strip():
        return existing.rstrip() + "\n\n" + generated + "\n"
    return generated + "\n"


def base_commit(base_ref: str) -> str:
    return git("rev-parse", base_ref).strip()


def stale_base(base_ref: str) -> str | None:
    """Why *base_ref* cannot be trusted as "the current default branch".

    Codex review: `--base-ref` defaults to `origin/main`, which is a
    remote-TRACKING ref -- a local cache of what origin looked like the last
    time this checkout fetched. From a checkout that has not fetched recently,
    both generation and tree validation succeed against a base that is already
    behind, and `--force-with-lease` does not help: it protects the
    demonstration branch refs, not the base they were built on. The result is
    a force-push of demos that are stale by construction, which is the exact
    invariant this script exists to hold.

    Asked with `ls-remote` rather than by fetching: reporting is not allowed to
    mutate the caller's refs, and an operator who is told precisely which
    fetch to run is better served than one whose repository changed under
    them. A base_ref that is not a remote-tracking ref (a SHA, a tag, a local
    branch) has no remote counterpart to compare, so it is left alone.
    """
    parts = base_ref.split("/", 1)
    if len(parts) != 2:
        return None
    remote, branch = parts
    tracking = f"refs/remotes/{remote}/{branch}"
    local = git("rev-parse", "--verify", "--quiet", tracking, check=False).strip()
    if not local:
        return None  # not a remote-tracking ref; nothing to compare against
    configured = git("remote", check=False).split()
    if remote not in configured:
        # `refs/remotes/<x>/...` can exist with no remote `<x>` configured
        # (hermetic tests build exactly that with `update-ref`). There is then
        # no upstream to be stale against -- distinct from a CONFIGURED remote
        # that cannot be reached, which stays an error below because currency
        # genuinely cannot be confirmed.
        return None
    listed = git("ls-remote", "--heads", remote, branch, check=False).strip()
    if not listed:
        return (
            f"could not reach {remote} to confirm {base_ref} is current "
            f"(`git ls-remote --heads {remote} {branch}` returned nothing). "
            "Fetch and retry, or pass --base-ref explicitly if this is "
            "deliberate."
        )
    upstream = listed.split()[0]
    if upstream != local:
        return (
            f"{base_ref} is stale: it points at {local[:12]} but {remote}/"
            f"{branch} is now {upstream[:12]}. Generating or pushing from here "
            f"would produce demonstrations that are already behind. Run "
            f"`git fetch {remote} {branch}` first."
        )
    return None


def expected_tree(demo: dict[str, Any], base_ref: str) -> str:
    """The tree a correctly generated branch would have: base + this patch.

    Built in a throwaway index (`GIT_INDEX_FILE` + `git apply --cached`), so
    it needs no checkout and touches neither the working tree nor the real
    index -- `--check` has to be safe to run anywhere, including on a branch
    someone is mid-edit on.
    """
    with tempfile.TemporaryDirectory() as tmp:
        env = {**os.environ, "GIT_INDEX_FILE": str(Path(tmp) / "index")}
        git("read-tree", f"{base_ref}^{{tree}}", env=env)
        git("apply", "--cached", str(REPO_ROOT / demo["patch"]), env=env)
        return git("write-tree", env=env).strip()


def check(demos: list[dict[str, Any]], base_ref: str) -> list[str]:
    """Report drift without touching anything.

    Codex review: this used to ask only whether the branch was behind the
    base (`rev-list <head>..<base>`), and separately whether the patch still
    applied to the local WORKING TREE. Neither question is the invariant. A
    branch rebuilt on today's base but carrying extra commits, or the same
    base with a hand-edited diff, answers "0 commits behind" and reports
    healthy -- which is exactly the silently-drifted long-lived demo this
    whole mechanism exists to make impossible. And checking the patch against
    the working tree checks it against whatever branch happens to be checked
    out, not against the base the branch would be regenerated from.

    So the invariant is asserted directly: the branch's TREE must equal the
    tree of base + its declared patch. That is content equality, so it is
    indifferent to commit messages, authorship and history shape, and it
    catches an extra commit, an edited patch and a stale base alike.
    """
    problems: list[str] = []
    # A stale base makes every verdict below wrong in the same direction:
    # branches would read as current against a base that has moved on.
    outdated = stale_base(base_ref)
    if outdated:
        problems.append(outdated)
    base = base_commit(base_ref)
    for demo in demos:
        branch = demo["branch"]
        remote = f"refs/remotes/origin/{branch.removeprefix('refs/heads/')}"
        head = git("rev-parse", "--verify", "--quiet", remote, check=False).strip()
        if not head:
            problems.append(f"{demo['id']}: {branch} does not exist on origin")
            continue

        # Reported separately from the tree mismatch below even though a
        # stale branch usually implies one: "you are N commits behind" is a
        # far more actionable message than "your tree hash differs".
        behind = git("rev-list", "--count", f"{head}..{base}").strip()
        if behind != "0":
            problems.append(
                f"{demo['id']}: {branch} is {behind} commit(s) behind {base_ref} "
                "-- regenerate it (--write, then --push)"
            )

        try:
            want = expected_tree(demo, base_ref)
        except DemoError as exc:
            # A patch that no longer applies to the CURRENT base has rotted
            # and needs a human before any branch is rewritten.
            problems.append(
                f"{demo['id']}: {demo['patch']} no longer applies to {base_ref}: {exc}"
            )
            continue
        got = git("rev-parse", f"{head}^{{tree}}").strip()
        if got != want:
            problems.append(
                f"{demo['id']}: {branch} is not {base_ref} + {demo['patch']} "
                f"(tree {got[:12]}, expected {want[:12]}) -- it carries extra or "
                "different changes; regenerate it (--write, then --push)"
            )
    return problems


def write(demos: list[dict[str, Any]], base_ref: str, only: str | None) -> list[str]:
    """Recreate each demonstration branch locally as base + its one patch."""
    outdated = stale_base(base_ref)
    if outdated:
        raise DemoError(f"refusing to generate against a stale base: {outdated}")
    written = []
    # Codex review: `rev-parse --abbrev-ref HEAD` returns the literal string
    # "HEAD" on a detached checkout, so restoring it with `git checkout HEAD`
    # is a no-op and leaves the caller sitting on the last generated branch --
    # a scoped regeneration silently moving someone's checkout, and most
    # likely exactly where it happens: automation and temporary worktrees.
    # Record what HEAD actually was: a branch name if symbolic, otherwise the
    # commit to detach back onto.
    original = git("symbolic-ref", "--quiet", "--short", "HEAD", check=False).strip()
    if not original:
        original = git("rev-parse", "HEAD").strip()
    if not original:
        raise DemoError("cannot determine the current HEAD to restore afterwards")
    if git("status", "--porcelain").strip():
        raise DemoError(
            "the working tree is dirty; regenerating demonstration branches "
            "checks branches out and would lose those changes"
        )
    try:
        for demo in demos:
            if only and demo["id"] != only:
                continue
            branch = demo["branch"]
            git("checkout", "-q", "-B", branch, base_ref)
            git("apply", str(REPO_ROOT / demo["patch"]))
            git("add", "-A")
            git("commit", "-q", "-m", demo["title"])
            written.append(f"{branch} = {base_ref} + {demo['patch']}")
    finally:
        problem = _restore_head(original)
        if problem:
            # Codex review: this used check=False and threw the result away,
            # so a failed restoration was silent and the caller was left on a
            # half-generated demonstration branch by code whose entire
            # purpose here is to put them back. Reachable: with a conflicting
            # local edit, `git checkout` refuses ("Your local changes would be
            # overwritten") and HEAD stays where it is -- verified directly.
            #
            # Raising from `finally` replaces an in-flight exception, and that
            # is the right precedence: whatever went wrong generating a
            # branch, the caller's checkout being silently wrong is the more
            # urgent fact, and Python keeps the original reachable as
            # __context__ so nothing is lost.
            raise DemoError(problem)
    return written


def _restore_head(original: str) -> str | None:
    """Put HEAD back where it was; return what went wrong, or None.

    `--detach` for a non-branch is what makes the detached case actually
    restore rather than creating a checkout of a branch that never existed.
    """
    is_branch = git(
        "rev-parse", "--verify", "--quiet", f"refs/heads/{original}", check=False
    ).strip()
    args = ("checkout", "-q", original) if is_branch else ("checkout", "-q", "--detach", original)
    try:
        git(*args)
    except DemoError as exc:
        landed = (
            git("symbolic-ref", "--quiet", "--short", "HEAD", check=False).strip()
            or git("rev-parse", "--short", "HEAD", check=False).strip()
            or "an unknown commit"
        )
        return (
            f"could not restore the checkout to {original!r}; it is left on "
            f"{landed!r}. Restore it by hand before rerunning: {exc}"
        )
    return None


def local_drift(demos: list[dict[str, Any]], base_ref: str) -> list[str]:
    """Why the LOCAL branches are not exactly base + their declared patch.

    Codex review: `--push` force-pushed whatever each local `test/*` ref
    happened to contain. `--force-with-lease` only detects a concurrent
    REMOTE update; it says nothing about whether the local content is valid,
    so a stale branch from an earlier generation, or one edited by hand, could
    overwrite a long-lived demonstration and break the generated-branch
    invariant the oracle depends on. `check()` cannot cover this: it inspects
    `refs/remotes/origin/*`, which is the state being replaced, not the state
    being pushed.
    """
    problems: list[str] = []
    for demo in demos:
        branch = demo["branch"]
        ref = f"refs/heads/{branch.removeprefix('refs/heads/')}"
        head = git("rev-parse", "--verify", "--quiet", ref, check=False).strip()
        if not head:
            problems.append(
                f"{demo['id']}: no local {branch} to push -- run --write first"
            )
            continue
        actual = git("rev-parse", f"{head}^{{tree}}").strip()
        wanted = expected_tree(demo, base_ref)
        if actual != wanted:
            problems.append(
                f"{demo['id']}: local {branch} is not {base_ref} plus "
                f"{demo['patch']} (tree {actual[:12]}, expected {wanted[:12]}) "
                "-- regenerate it with --write instead of pushing it"
            )
    return problems


def push(demos: list[dict[str, Any]], only: str | None, base_ref: str) -> list[str]:
    # Validate before the FIRST push, not per branch: a force-push is not
    # undoable, so pushing two valid branches and then refusing on the third
    # would leave the set half-replaced.
    outdated = stale_base(base_ref)
    if outdated:
        raise DemoError(f"refusing to force-push from a stale base: {outdated}")
    problems = local_drift(
        [demo for demo in demos if not only or demo["id"] == only], base_ref
    )
    if problems:
        raise DemoError(
            "refusing to force-push: the local branches are not the generated "
            "trees:\n  " + "\n  ".join(problems)
        )
    pushed = []
    for demo in demos:
        if only and demo["id"] != only:
            continue
        branch = demo["branch"]
        # --force-with-lease, not --force: if someone pushed to a
        # demonstration branch since this checkout last fetched it, that is a
        # human decision this script must not silently discard.
        git("push", "--force-with-lease", "origin", f"{branch}:{branch}")
        pushed.append(branch)
    return pushed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--manifest", type=Path, default=REPO_ROOT / "demos/manifest.yaml")
    parser.add_argument("--base-ref", default="origin/main")
    parser.add_argument("--only", help="act on one demonstration id")
    parser.add_argument("--check", action="store_true", help="report drift, change nothing")
    parser.add_argument("--write", action="store_true", help="recreate the branches locally")
    parser.add_argument("--push", action="store_true", help="force-push the branches")
    parser.add_argument("--body", help="print the PR-body section for this demonstration id")
    args = parser.parse_args(argv)

    if not any((args.check, args.write, args.push, args.body)):
        parser.error("one of --check, --write, --push or --body is required")

    try:
        demos = load_manifest(args.manifest)
        if args.only:
            # Codex review: --check used the full list while --write and
            # --push filtered, so `--check --only <id>` failed on drift in a
            # branch the operator had not asked about -- contradicting both
            # the flag's help text and its behaviour for the other two modes.
            # Filtering once here makes every mode honour it, and an unknown
            # id is now an error rather than a silent no-op that reports
            # success for having checked nothing.
            selected = [demo for demo in demos if demo["id"] == args.only]
            if not selected:
                raise DemoError(
                    f"no demonstration {args.only!r}; known ids: "
                    + ", ".join(sorted(demo["id"] for demo in demos))
                )
            demos = selected
        if args.body:
            match = next((d for d in demos if d["id"] == args.body), None)
            if match is None:
                raise DemoError(f"no demonstration {args.body!r}")
            print(render_body(match))
            return 0
        if args.check:
            problems = check(demos, args.base_ref)
            for problem in problems:
                print(f"DRIFT {problem}", file=sys.stderr)
            if problems:
                return 1
            print(f"gen_demo_prs: OK -- {len(demos)} demonstration(s) current against {args.base_ref}")
        if args.write:
            for line in write(demos, args.base_ref, None):
                print(f"wrote {line}")
        if args.push:
            for branch in push(demos, None, args.base_ref):
                print(f"pushed {branch}")
    except DemoError as exc:
        print(f"gen_demo_prs: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
