#!/usr/bin/env python3
"""Resolve, classify, and receipt the accepted-main baseline for a PR.

The native project path compares a PR against the *accepted-main* baseline
for its base commit.  Three separate identities have to line up for that to
work, and when they do not the failure used to surface as a bare
``FileNotFoundError: baseline-set/manifest.json`` with nothing to diagnose:

1. the commit the PR asks to be compared against (its base SHA);
2. the commit whose baseline was actually published (the accepted-main
   refresh runs on ``push: main``, and a bot-authored baseline-refresh
   commit pushed with automation credentials starts no workflow run at all,
   so it never gets a baseline of its own);
3. the identity recorded inside the restored ``manifest.json``
   (``profile`` / ``project_ref`` / ``baseline_generation``).

This module makes all three explicit.  ``resolve`` walks a PR base back to
the nearest commit that can own a baseline, ``classify`` decides whether a
restored baseline-set may be used for that comparison, and both emit the
same machine-readable receipt so a red job says exactly which identity was
rejected and why.

The receipt is the contract; ``reason_selected`` is its verdict:

``exact-base``
    The restored manifest is the PR base commit's own baseline.
``abi-equivalent-ancestor``
    The PR base is separated from the restored manifest's commit only by
    commits that touch nothing the ABI depends on (see ``ABI_NEUTRAL_PATHS``),
    so that ancestor's baseline *is* this base's baseline.
``rebuilt-from-source-commit``
    No usable baseline-set was in the cache (caches are evicted and expire),
    so one was rebuilt from the resolved source commit.  The accepted-main
    baseline is defined by that commit, not by the cache entry; the cache is
    only transport.  Recorded distinctly so a run that never had a cache is
    never mistaken for one that did.

Anything else is a rejection and names the identity that did not match.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Sequence

# Path prefixes whose contents cannot change the ABI of anything the native
# project builds.  `abi/` holds the *committed legacy snapshots* the older
# scan workflows compare against; a bot-authored "chore: refresh ABICheck
# baseline" commit touches nothing else.  Keep this list minimal: every
# entry added here is a class of change the lab stops noticing.
ABI_NEUTRAL_PATHS: tuple[str, ...] = ("abi/",)

# Rejection reasons.  Distinct from the accepting `reason_selected` values so
# a receipt never has to be read together with a separate ok/not-ok flag.
REASON_EXACT_BASE = "exact-base"
REASON_ABI_EQUIVALENT_ANCESTOR = "abi-equivalent-ancestor"
REASON_REBUILT = "rebuilt-from-source-commit"

REJECT_CACHE_MISS = "cache-miss"
REJECT_MISSING_MANIFEST = "missing-manifest"
REJECT_MALFORMED_MANIFEST = "malformed-manifest"
REJECT_WRONG_PROFILE = "wrong-profile"
REJECT_WRONG_PROJECT_REF = "wrong-project-ref"
REJECT_STALE_GENERATION = "stale-generation"
# Codex review: the candidate side of every comparison is scanned with the
# workflow's CURRENT scanner pin, but a restored cache holds a baseline
# generated by whatever pin was current when it was written. Classification
# checked profile, project ref and generation -- never the generator -- so a
# pin bump made the comparison depend on cache availability: a surviving
# cache compared old-generator baseline against new-generator candidate,
# while an expired one rebuilt with the new pin and compared like for like.
# Two different extractions, silently selected by a cache's age.
#
# One generator identity for both sides is the invariant, so a baseline whose
# generator is not this run's is rejected. Rejection here is cheap and safe:
# it does not turn the gate red, it falls through to the rebuild path, which
# regenerates with the current pin -- exactly the like-for-like comparison
# that was wanted. An absent generator is rejected for the same reason; a
# cache written before this field existed records an unknown extraction, and
# unknown is not "matching".
REJECT_WRONG_GENERATOR = "wrong-generator"
REJECT_UNKNOWN_GENERATOR = "unknown-generator"

ACCEPTING_REASONS = frozenset(
    {REASON_EXACT_BASE, REASON_ABI_EQUIVALENT_ANCESTOR, REASON_REBUILT}
)


class ResolutionError(RuntimeError):
    """A resolution input was unusable (bad git state, unreadable file)."""


def _git(repo: Path, *args: str) -> str:
    proc = subprocess.run(
        ["git", "-C", str(repo), *args],
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        raise ResolutionError(
            f"git {' '.join(args)} failed ({proc.returncode}): {proc.stderr.strip()}"
        )
    return proc.stdout


def _git_optional(repo: Path, *args: str) -> Optional[str]:
    try:
        return _git(repo, *args)
    except ResolutionError:
        return None


def is_abi_neutral(paths: Sequence[str]) -> bool:
    """True when every changed path is known not to affect the built ABI.

    An empty change set is *not* neutral: a commit that changes nothing is
    not evidence that it is safe to reuse its parent's baseline, it is
    evidence that the diff could not be computed.
    """
    if not paths:
        return False
    return all(
        any(path.startswith(prefix) for prefix in ABI_NEUTRAL_PATHS) for path in paths
    )


def git_changed_paths(repo: Path) -> Callable[[str, str], Optional[List[str]]]:
    """Return a `--no-renames` name-only differ bound to `repo`.

    `--no-renames` matters: git's default rename detection reports a moved
    file under a single entry, so a rename *out of* an ABI-neutral prefix can
    read as an ABI-neutral change.  Every ancestry classification in this
    repository uses it (see .github/actions/skip-check/action.yml).
    """

    def changed(parent: str, child: str) -> Optional[List[str]]:
        out = _git_optional(repo, "diff", "--no-renames", "--name-only", parent, child)
        if out is None:
            return None
        return [line for line in out.splitlines() if line]

    return changed


def resolve_source_commit(
    requested: str,
    changed_paths: Callable[[str, str], Optional[List[str]]],
    parent_of: Callable[[str], Optional[str]],
    *,
    max_steps: int = 50,
) -> Dict[str, Any]:
    """Walk `requested` back to the nearest commit that can own a baseline.

    Stops at the first commit whose diff from its first parent is not
    ABI-neutral, at the first commit with no parent, and after `max_steps`
    (a corrupt or pathological history must not spin forever -- it must
    fail closed with the walk it managed).
    """
    if not requested:
        raise ResolutionError("no requested PR base commit was supplied")
    selected = requested
    skipped: List[Dict[str, Any]] = []
    truncated = False
    for _ in range(max_steps):
        parent = parent_of(selected)
        if not parent:
            break
        paths = changed_paths(parent, selected)
        if paths is None or not is_abi_neutral(paths):
            break
        skipped.append({"commit": selected, "parent": parent, "changed": sorted(paths)})
        selected = parent
    else:
        truncated = True
    return {
        "requested_pr_base": requested,
        "selected_source_commit": selected,
        "abi_neutral_commits_skipped": skipped,
        "walk_truncated": truncated,
        "reason_selected": (
            REASON_EXACT_BASE if selected == requested else REASON_ABI_EQUIVALENT_ANCESTOR
        ),
    }


def _load_manifest(baseline_dir: Path) -> tuple[Optional[Dict[str, Any]], Optional[str]]:
    manifest_path = baseline_dir / "manifest.json"
    if not manifest_path.is_file():
        return None, REJECT_MISSING_MANIFEST
    try:
        raw = manifest_path.read_text(encoding="utf-8")
    except OSError:
        return None, REJECT_MISSING_MANIFEST
    except UnicodeDecodeError:
        # A truncated or byte-corrupted cache entry must be an operational
        # rejection with a receipt, never an uncaught decode traceback.
        return None, REJECT_MALFORMED_MANIFEST
    try:
        manifest = json.loads(raw)
    except json.JSONDecodeError:
        return None, REJECT_MALFORMED_MANIFEST
    if not isinstance(manifest, dict):
        return None, REJECT_MALFORMED_MANIFEST
    return manifest, None


def classify(
    *,
    requested_pr_base: str,
    selected_source_commit: str,
    profile: str,
    expected_generation: int,
    cache_primary_key: str,
    cache_matched_key: Optional[str],
    baseline_dir: Path,
    rebuilt: bool = False,
    expected_generator: Optional[str] = None,
    available_cache_keys: Optional[Sequence[str]] = None,
    abi_neutral_commits_skipped: Optional[Sequence[Dict[str, Any]]] = None,
) -> Dict[str, Any]:
    """Decide whether `baseline_dir` may serve as this comparison's baseline."""
    receipt: Dict[str, Any] = {
        "requested_pr_base": requested_pr_base,
        "selected_source_commit": selected_source_commit,
        "cache_primary_key": cache_primary_key,
        "cache_matched_key": cache_matched_key or None,
        "manifest_project_ref": None,
        "manifest_generation": None,
        "reason_selected": None,
        "profile": profile,
        "expected_baseline_generation": expected_generation,
        "manifest_profile": None,
        "manifest_generator_git_sha": None,
        "expected_generator_git_sha": expected_generator,
        "abi_neutral_commits_skipped": list(abi_neutral_commits_skipped or []),
        "usable": False,
    }
    if available_cache_keys is not None:
        receipt["available_cache_keys"] = list(available_cache_keys)

    if not rebuilt and not cache_matched_key:
        receipt["reason_selected"] = REJECT_CACHE_MISS
        return receipt

    manifest, failure = _load_manifest(baseline_dir)
    if failure is not None:
        receipt["reason_selected"] = failure
        return receipt

    receipt["manifest_profile"] = manifest.get("profile")
    receipt["manifest_project_ref"] = manifest.get("project_ref")
    receipt["manifest_generation"] = manifest.get("baseline_generation")
    receipt["manifest_generator_git_sha"] = manifest.get("generator_git_sha")

    if receipt["manifest_profile"] != profile:
        receipt["reason_selected"] = REJECT_WRONG_PROFILE
        return receipt
    if receipt["manifest_project_ref"] != selected_source_commit:
        receipt["reason_selected"] = REJECT_WRONG_PROJECT_REF
        return receipt
    if receipt["manifest_generation"] != expected_generation:
        receipt["reason_selected"] = REJECT_STALE_GENERATION
        return receipt
    if expected_generator is not None:
        recorded = receipt["manifest_generator_git_sha"]
        if not recorded:
            receipt["reason_selected"] = REJECT_UNKNOWN_GENERATOR
            return receipt
        if recorded != expected_generator:
            receipt["reason_selected"] = REJECT_WRONG_GENERATOR
            return receipt

    if rebuilt:
        reason = REASON_REBUILT
    elif selected_source_commit == requested_pr_base:
        reason = REASON_EXACT_BASE
    else:
        reason = REASON_ABI_EQUIVALENT_ANCESTOR
    receipt["reason_selected"] = reason
    receipt["usable"] = True
    return receipt


def _write_outputs(pairs: Dict[str, str]) -> None:
    path = os.environ.get("GITHUB_OUTPUT")
    if not path:
        return
    with open(path, "a", encoding="utf-8") as handle:
        for key, value in pairs.items():
            handle.write(f"{key}={value}\n")


def _emit(receipt: Dict[str, Any], out: Optional[Path]) -> None:
    text = json.dumps(receipt, indent=2, sort_keys=True)
    print(text)
    if out is not None:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text + "\n", encoding="utf-8")


def _read_available_keys(path: Optional[Path]) -> Optional[List[str]]:
    """Best-effort read of the cache-key listing the workflow curled for us.

    Purely diagnostic: a listing that cannot be read must never change the
    verdict, only how much the receipt can explain about it.
    """
    if path is None or not path.is_file():
        return None
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError):
        return None
    entries = payload.get("actions_caches") if isinstance(payload, dict) else None
    if not isinstance(entries, list):
        return None
    return sorted(
        {entry.get("key") for entry in entries if isinstance(entry, dict) and entry.get("key")}
    )


def _cmd_resolve(args: argparse.Namespace) -> int:
    repo = args.repo
    result = resolve_source_commit(
        args.requested,
        git_changed_paths(repo),
        lambda sha: (_git_optional(repo, "rev-parse", f"{sha}^") or "").strip() or None,
    )
    _emit(result, args.out)
    _write_outputs(
        {
            "requested_pr_base": result["requested_pr_base"],
            "sha": result["selected_source_commit"],
            "walk": json.dumps(result["abi_neutral_commits_skipped"]),
        }
    )
    return 0


def _cmd_classify(args: argparse.Namespace) -> int:
    skipped = json.loads(args.walk) if args.walk else []
    receipt = classify(
        requested_pr_base=args.requested,
        selected_source_commit=args.selected,
        profile=args.profile,
        expected_generation=args.expected_generation,
        cache_primary_key=args.primary_key,
        cache_matched_key=args.matched_key,
        baseline_dir=args.baseline_dir,
        rebuilt=args.rebuilt,
        expected_generator=args.expected_generator or None,
        available_cache_keys=_read_available_keys(args.cache_listing),
        abi_neutral_commits_skipped=skipped,
    )
    _emit(receipt, args.out)
    _write_outputs({"usable": "true" if receipt["usable"] else "false",
                    "reason": receipt["reason_selected"]})
    if receipt["usable"] or args.no_fail:
        return 0
    print(
        f"ERROR: accepted-main baseline rejected: {receipt['reason_selected']}",
        file=sys.stderr,
    )
    return 1


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    resolve = sub.add_parser("resolve", help="walk a PR base to its baseline-owning commit")
    resolve.add_argument("--requested", required=True)
    resolve.add_argument("--repo", type=Path, default=Path.cwd())
    resolve.add_argument("--out", type=Path)
    resolve.set_defaults(func=_cmd_resolve)

    check = sub.add_parser("classify", help="receipt a restored or rebuilt baseline-set")
    check.add_argument("--requested", required=True)
    check.add_argument("--selected", required=True)
    check.add_argument("--profile", required=True)
    check.add_argument("--expected-generation", type=int, default=1)
    check.add_argument(
        "--expected-generator",
        help="the scanner pin this run scans the candidate with; a baseline "
             "generated by a different one is rejected so the rebuild path "
             "regenerates it like for like",
    )
    check.add_argument("--primary-key", required=True)
    check.add_argument("--matched-key", default="")
    check.add_argument("--baseline-dir", type=Path, default=Path("baseline-set"))
    check.add_argument("--walk", default="")
    check.add_argument("--out", type=Path)
    check.add_argument("--cache-listing", type=Path)
    check.add_argument(
        "--rebuilt",
        action="store_true",
        help="the baseline-set was rebuilt from the source commit, not restored",
    )
    check.add_argument(
        "--no-fail",
        action="store_true",
        help="always exit 0; the receipt still records the verdict",
    )
    check.set_defaults(func=_cmd_classify)

    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except ResolutionError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
